spring:
    application:
        name: vanta-gateway
    config:
        import:
            - optional:nacos:gateway.yaml
    cloud:
        nacos:
            serverAddr: 127.0.0.1:8848
            config:
                namespace: vanta
                group: TEST_GROUP
            discovery:
                namespace: vanta
                group: TEST_GROUP
                port: ${network.port}
