spring:
    application:
        name: vanta-consumer
    config:
        import:
            - optional:nacos:consumer.yaml
    cloud:
        nacos:
            serverAddr: 127.0.0.1:8848
            config:
                namespace: vanta
                group: TEST_GROUP
            discovery:
                namespace: vanta
                group: TEST_GROUP
                port: 8848
